import type { Metadata } from 'next'
import { Geist } from 'next/font/google'
import './globals.css'
import Provider from '@/lib/provider'
import { SidebarTrigger } from '@/components/ui/sidebar'
import { AppSidebar } from '@/components/layout/AppSidebar'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body className={`${geistSans.variable} antialiased`}>
        <Provider>
          <AppSidebar />

          {children}
        </Provider>
      </body>
    </html>
  )
}
